"""The CV10 ledger checker — the thing the live battery trusts when it says a scenario passed.

Two properties matter here, and they pull in opposite directions:

1. It must FAIL, by name, on a broken join. A battery that reads "no violations" off a ledger
   whose turn events do not pair has learned nothing and will say it learned something.
2. It must not cry wolf on a HEALTHY ledger. The emitter omits None-valued fields rather than
   writing nulls, so half the schema is legitimately absent on any given line; a checker that
   demands every key would fire on every real file and be switched off within a day.

So the assertions are on violation NAMES (prose is free to change), and the headline fixture is
generated by CALLING THE REAL EMITTER — a checker validated only against hand-written fixtures
agrees with the fixture author rather than with the writer.

The checker itself is run as a SUBPROCESS, by path, from a directory that is not the repo. That is
not paranoia about imports: "runs against a ledger copied off a machine with no venv" is a
requirement, and a subprocess with only `tools/` on sys.path is the only way to test it.
"""
from __future__ import annotations

import json
import logging
import subprocess
import sys
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
CHECKER = REPO_ROOT / "tools" / "participation_ledger_check.py"

SESSION = "S1"


# ------------------------------------------------------------------------------ the harness

def run_checker(*paths, extra=()):
    """Run the CLI. cwd is deliberately NOT the repo, so a repo import would explode here."""
    argv = [sys.executable, str(CHECKER), *[str(p) for p in paths], *extra]
    return subprocess.run(argv, capture_output=True, text=True, cwd=str(Path(paths[0]).parent)
                          if paths else None)


def check(*paths):
    """(exit code, parsed --json report)."""
    result = run_checker(*paths, extra=("--json",))
    assert result.stderr == "", result.stderr
    return result.returncode, json.loads(result.stdout)


def names(payload):
    return set(payload["violation_counts"])


def warning_names(payload):
    return {w["name"] for w in payload["warnings"]}


def envelope(event, *, session=SESSION, version=10, contract="binary-v1", **fields):
    """One line, built the way `record()` builds it: None-valued fields are OMITTED."""
    row = {"v": version, "at": 1_700_000_000.0, "session": session, "event": event}
    if contract is not None:
        row["gate_contract"] = contract
    row.update({key: value for key, value in fields.items() if value is not None})
    return row


def stream_render_payload(**overrides):
    """Every §8 field, because every one of them is MANDATORY on a stream_render row.

    A fixture carrying a handful of fields was legal until the checker learned the contract;
    once it did, a minimal row is exactly the defect the contract exists to catch, so the
    fixtures widen in the same change that makes the fields mandatory rather than after it.
    """
    payload = {
        "channel_id": "C1", "H": "1.9",
        "periphery_floor_ts": "1.0", "inventory_start_ts": "0.5", "inventory_state": "warm",
        "stream_sha256": "f" * 64, "union_sha256": "e" * 64,
        "serializer_config_hash": "d" * 64, "sidecar_versions_hash": "c" * 64,
        "actor_map_hash": "b" * 64, "receipts_membership_hash": "a" * 64,
        "capability_profile_hash": "9" * 64,
        "byte_count": 420, "origin_byte_count": 120, "message_count": 7, "origin_count": 2,
        "candidate_count": 9, "root_count": 3, "orphan_root_count": 0,
        "receipts_included_count": 1, "receipts_excluded_count": 0,
        "history_pages": 1, "reply_pages": 0, "origin_pages": 1,
        "selection_version": 1, "serializer_version": 3,
        "reselected": False, "anchor_advanced": False,
    }
    payload.update(overrides)
    return payload


def healthy_rows(session=SESSION):
    """One gated channel turn that answered, start to finish, with every v8 event present.

    Ids are derived from the session, because they are unique per PROCESS in the real ledger and
    a fixture that reuses them across two sessions manufactures duplicate-join violations.
    """
    turn_id, attempt_id = f"t-{session}", f"a-{session}"
    return [
        envelope("session_start", session=session, build="deadbee"),
        envelope("gate_start", session=session, channel_id="C1", trigger_ts="1.0",
                 attempt_id=attempt_id, level="judicious"),
        envelope("gate_decision", session=session, channel_id="C1", trigger_ts="1.0",
                 attempt_id=attempt_id, wake=True, model="gpt-5.6-luna"),
        envelope("turn_start", session=session, channel_id="C1", trigger_ts="1.0",
                 turn_id=turn_id, surface="channel", gated=True, attempt_id=attempt_id),
        envelope("stream_render", session=session, trigger_ts="1.0",
                 turn_id=turn_id, origin_thread_ts="1.0", **stream_render_payload()),
        envelope("model_response", session=session, turn_id=turn_id, attempt_seq=1, status="ok",
                 model="gpt-5.6-sol", input_tokens=100, output_tokens=10),
        envelope("outbound_receipt", session=session, channel_id="C1", message_ts="2.0",
                 owner_turn_id=turn_id, op="register", prior_state="absent",
                 new_state="in_flight", applied=True),
        envelope("turn_outcome", session=session, channel_id="C1", trigger_ts="1.0",
                 turn_id=turn_id, attempt_id=attempt_id, kind="reply", chars=12,
                 detached_started=False, stream_build_present=True,
                 destinations=[{"channel_id": "C1", "thread_root_ts": "1.0", "first_ts": "2.0",
                                "state": "committed", "chars": 12, "kind": "reply"}],
                 edits=[]),
        envelope("visible_action", session=session, channel_id="C1", trigger_ts="1.0",
                 kind="reply", attempt_id=attempt_id, gate_woke=True, responder_started=True,
                 reaction_visible=False, destination="thread",
                 destination_source="structural"),
        envelope("session_end", session=session),
    ]


def write_ledger(tmp_path, rows, name="participation.jsonl"):
    path = tmp_path / name
    path.write_text("".join(json.dumps(row) + "\n" for row in rows))
    return path


def row_index(rows, event):
    return next(i for i, row in enumerate(rows) if row["event"] == event)


# ------------------------------------------------------------------------ the healthy ledger

def test_a_ledger_written_by_the_real_emitter_passes(tmp_path):
    """THE ROUND TRIP. Everything else here is a fixture I wrote; this one is the file the bot
    actually writes, through the real `record()`, the real omit-None rule, the real
    `emit_turn_outcome` assembler and the real `finish_attempt` terminal guard."""
    from config import config
    from message_processor import participation_telemetry as pt
    from message_processor.turn_runtime import DestinationRecord

    named = logging.getLogger(pt._SINK_LOGGER_NAME)
    saved = named.handlers[:]
    pt.shutdown()
    try:
        with patch.object(config, "log_directory", str(tmp_path)), \
                patch.object(config, "enable_participation_telemetry", True):
            pt.initialize()
            pt.gate_start("C1", "1.0", attempt_id="a1", level="judicious", thread_reply=False)
            pt.gate_decision("C1", "1.0", wake=True, attempt_id="a1", gate_ms=900,
                             classifier_ms=400, source_count=1)
            pt.turn_start("C1", "1.0", turn_id="t1", origin_thread_ts="1.0", surface="channel",
                          gated=True, attempt_id="a1")
            # THE FULL FIELD SET, exactly as `_emit_stream_render` sends it in production —
            # it splats `stream.stream_render_fields()`, so a hand-call carrying a handful of
            # fields would make this round trip prove less than the real path does.
            pt.stream_render(turn_id="t1", origin_thread_ts="1.0", trigger_ts="1.0",
                             **stream_render_payload())
            pt.model_response(turn_id="t1", attempt_seq=1, status="ok", model="gpt-5.6-sol",
                              input_tokens=100, output_tokens=10, cached_input_tokens=64)
            pt.outbound_receipt(channel_id="C1", message_ts="2.0", owner_turn_id="t1",
                                op="register", prior_state="absent", new_state="in_flight",
                                applied=True)

            # The real assembler, over the real destination record.
            record = DestinationRecord(channel_id="C1", thread_root_ts="1.0", first_ts="2.0",
                                       kind="reply")
            record.state = "committed"
            record.chars = 12
            turn = SimpleNamespace(turn_id="t1", destinations=[record], turn_error=None,
                                   H="1.9", stream_build_present=True)
            assert pt.emit_turn_outcome(turn, channel_id="C1", trigger_ts="1.0", kind="reply",
                                        attempt_id="a1")

            # The real terminal path, closed-flag guard and all.
            message = SimpleNamespace(metadata={pt.ATTEMPT_KEY: "a1", "ts": "1.0"},
                                      channel_id="C1", thread_id="1.0")
            assert pt.finish_attempt(message, "reply", reaction_visible=False)
            pt._drain()
            pt.shutdown()   # writes session_end and drains it

            ledger = tmp_path / pt.LOG_NAME
            code, payload = check(ledger)
            assert payload["violations"] == []
            assert payload["warnings"] == []
            assert code == 0, payload
            assert payload["counts"]["graded_lines"] > 0
    finally:
        pt.shutdown()
        named.handlers = saved


def test_the_handwritten_healthy_fixture_agrees_with_the_emitter(tmp_path):
    code, payload = check(write_ledger(tmp_path, healthy_rows()))
    assert (code, payload["violations"], payload["warnings"]) == (0, [], [])
    assert payload["verdict"] == "pass" and payload["ok"] is True


def test_legal_absences_are_not_violations(tmp_path):
    """The emitter omits None. A minimal-but-honest turn — no chars, no error, no H, an ungated
    turn with no attempt_id, a receipt with no prior state, a destination whose thread root and
    char count are null — is HEALTHY."""
    rows = [
        envelope("session_start", build="deadbee"),
        envelope("turn_start", channel_id="C1", trigger_ts="1.0", turn_id="t9",
                 surface="channel", gated=False),
        envelope("turn_outcome", channel_id="C1", trigger_ts="1.0", turn_id="t9",
                 kind="silence", detached_started=False, stream_build_present=False,
                 destinations=[{"channel_id": "C1", "thread_root_ts": None, "first_ts": "2.0",
                                "state": "observed", "chars": None, "kind": "stream"}],
                 edits=[]),
        envelope("outbound_receipt", channel_id="C1", message_ts="2.0", owner_turn_id="t9",
                 op="pending_resolve", new_state="finalized", applied=True),
        envelope("session_end"),
    ]
    code, payload = check(write_ledger(tmp_path, rows))
    assert (code, payload["violations"]) == (0, [])


# ---------------------------------------------------------------- invariant 1: turn pairing

def test_a_turn_start_with_no_outcome_fails(tmp_path):
    rows = healthy_rows()
    del rows[row_index(rows, "turn_outcome")]
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "turn_outcome_missing" in names(payload)


def test_an_outcome_with_no_start_is_a_different_violation(tmp_path):
    rows = healthy_rows()
    del rows[row_index(rows, "turn_start")]
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "turn_outcome_orphan" in names(payload)
    assert "turn_outcome_missing" not in names(payload)


def test_two_outcomes_for_one_turn_is_a_third_violation(tmp_path):
    rows = healthy_rows()
    rows.insert(-1, dict(rows[row_index(rows, "turn_outcome")]))
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "turn_outcome_duplicate" in names(payload)
    assert not {"turn_outcome_missing", "turn_outcome_orphan"} & names(payload)


def test_two_starts_for_one_turn_is_its_own_violation(tmp_path):
    rows = healthy_rows()
    rows.insert(-1, dict(rows[row_index(rows, "turn_start")]))
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "turn_start_duplicate" in names(payload)


def test_a_truncated_tail_is_a_warning_not_a_violation(tmp_path):
    """No session_end means a crash, and a crash loses the records still queued. The turn may
    well have finished; complaining about it would make every killed process a red build."""
    rows = healthy_rows()
    del rows[row_index(rows, "session_end")]
    del rows[row_index(rows, "turn_outcome")]
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 0, payload["violations"]
    assert "turn_outcome_missing" in warning_names(payload)
    assert payload["counts"]["truncated_tail_unmatched_turn_start"] == 1
    assert payload["counts"]["tail_session_open"] == 1


def test_an_unmatched_start_in_a_closed_session_still_fails(tmp_path):
    """Same missing outcome, but this session DID say goodbye — so nothing was lost in transit
    and the turn genuinely never reported what it did."""
    first = healthy_rows("older")
    del first[row_index(first, "turn_outcome")]
    rows = first + healthy_rows("newest")
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "turn_outcome_missing" in names(payload)


# ------------------------------------------------------------ invariant 2: stream_render joins

def test_stream_render_with_no_turn_start_fails(tmp_path):
    rows = healthy_rows()
    rows[row_index(rows, "stream_render")]["turn_id"] = "ghost"
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "stream_render_orphan_turn" in names(payload)


def test_stream_render_with_no_turn_id_at_all_fails(tmp_path):
    rows = healthy_rows()
    del rows[row_index(rows, "stream_render")]["turn_id"]
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "stream_render_missing_turn_id" in names(payload)


def test_a_turn_that_claims_a_build_and_rendered_nothing_fails(tmp_path):
    rows = healthy_rows()
    del rows[row_index(rows, "stream_render")]
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "stream_render_absent_for_build" in names(payload)


def test_a_turn_that_denies_a_build_and_rendered_one_fails(tmp_path):
    rows = healthy_rows()
    rows[row_index(rows, "turn_outcome")]["stream_build_present"] = False
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "stream_render_without_build" in names(payload)


# -------------------------------------------------------- invariant 3: the terminal invariant

def test_two_terminals_for_one_attempt_fails(tmp_path):
    rows = healthy_rows()
    rows.insert(-1, dict(rows[row_index(rows, "visible_action")]))
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "visible_action_duplicate" in names(payload)


def test_a_terminal_with_no_gate_start_fails(tmp_path):
    rows = healthy_rows()
    del rows[row_index(rows, "gate_start")]
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "visible_action_orphan_attempt" in names(payload)


def test_a_terminal_with_no_attempt_id_fails(tmp_path):
    rows = healthy_rows()
    del rows[row_index(rows, "visible_action")]["attempt_id"]
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "visible_action_missing_attempt_id" in names(payload)


def test_a_turn_outcome_is_never_counted_as_a_terminal(tmp_path):
    """THE POPULATION SEPARATION. This attempt has a turn_outcome carrying its attempt_id and no
    visible_action. If turn events could close an attempt, the terminal count would be 1 and the
    unmatched gate_start would vanish. Both denominators are reported, and neither moves."""
    rows = healthy_rows()
    del rows[row_index(rows, "visible_action")]
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 0, payload["violations"]
    assert payload["denominators"] == {"gate_start": 1, "visible_action": 0,
                                       "turn_start": 1, "turn_outcome": 1,
                                       "turn_start_dm": 0, "turn_outcome_dm": 0}
    assert "gate_start_without_terminal" in warning_names(payload)
    assert "turn_event_in_terminal_population" not in names(payload)


# --------------------------------------------------------------- invariant 4: version stamps

def test_a_line_missing_its_identity_fails(tmp_path):
    rows = healthy_rows()
    del rows[row_index(rows, "gate_start")]["session"]
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "missing_envelope_field" in names(payload)


def test_a_foreign_gate_contract_fails(tmp_path):
    rows = healthy_rows()
    rows[row_index(rows, "gate_decision")]["gate_contract"] = "rich-v1"
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "bad_gate_contract" in names(payload)


def test_a_future_contract_version_is_refused_rather_than_graded(tmp_path):
    rows = healthy_rows()
    rows[row_index(rows, "turn_outcome")]["v"] = 11
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "unknown_contract_version" in names(payload)


def test_older_contract_lines_are_skipped_and_reported(tmp_path):
    """The file rotates across a deploy, so a mixed file is NORMAL. v7 rows have no turn events
    at all; grading them by v8 rules would invent violations out of correct history."""
    old = [envelope("gate_start", session="v7run", version=7, channel_id="C1",
                    trigger_ts="0.1", attempt_id="old1"),
           envelope("visible_action", session="v7run", version=7, channel_id="C1",
                    trigger_ts="0.1", kind="silence", attempt_id="old1"),
           envelope("turn_start", session="v7run", version=7, channel_id="C1",
                    trigger_ts="0.1", turn_id=None)]
    code, payload = check(write_ledger(tmp_path, old + healthy_rows()))
    assert code == 0, payload["violations"]
    assert payload["counts"]["skipped_older_contract"] == 3
    assert payload["counts"]["skipped_v7"] == 3
    assert payload["denominators"]["gate_start"] == 1   # the v7 attempt is not in the population


# ------------------------------------------------------------ invariant 5: payload spot checks

def test_receipt_with_an_unknown_op_fails(tmp_path):
    rows = healthy_rows()
    rows[row_index(rows, "outbound_receipt")]["op"] = "reconcile"
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "outbound_receipt_bad_op" in names(payload)


def test_receipt_with_an_unknown_state_fails(tmp_path):
    rows = healthy_rows()
    rows[row_index(rows, "outbound_receipt")]["new_state"] = "done"
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "outbound_receipt_bad_state" in names(payload)


def test_receipt_whose_applied_is_not_a_bool_fails(tmp_path):
    """A truthy string would make every "did it land?" count come out silently correct."""
    rows = healthy_rows()
    rows[row_index(rows, "outbound_receipt")]["applied"] = "true"
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "outbound_receipt_applied_not_bool" in names(payload)


def test_receipt_missing_its_owner_fails(tmp_path):
    rows = healthy_rows()
    del rows[row_index(rows, "outbound_receipt")]["owner_turn_id"]
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "outbound_receipt_missing_field" in names(payload)


def test_a_refused_receipt_with_no_reason_is_only_a_warning(tmp_path):
    rows = healthy_rows()
    receipt = rows[row_index(rows, "outbound_receipt")]
    receipt["applied"] = False
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 0, payload["violations"]
    assert "outbound_receipt_refused_without_reason" in warning_names(payload)


def test_destination_with_an_unknown_state_fails(tmp_path):
    rows = healthy_rows()
    rows[row_index(rows, "turn_outcome")]["destinations"][0]["state"] = "sent"
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "turn_outcome_destination_bad_state" in names(payload)


def test_destination_with_an_unknown_kind_fails(tmp_path):
    rows = healthy_rows()
    rows[row_index(rows, "turn_outcome")]["destinations"][0]["kind"] = "canvas"
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "turn_outcome_destination_bad_kind" in names(payload)


def test_destination_missing_a_key_fails(tmp_path):
    rows = healthy_rows()
    del rows[row_index(rows, "turn_outcome")]["destinations"][0]["first_ts"]
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "turn_outcome_destination_malformed" in names(payload)


def test_destinations_that_are_not_a_list_fails(tmp_path):
    rows = healthy_rows()
    rows[row_index(rows, "turn_outcome")]["destinations"] = {"channel_id": "C1"}
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "turn_outcome_destinations_not_list" in names(payload)


def test_turn_outcome_kind_outside_the_terminal_vocabulary_fails(tmp_path):
    rows = healthy_rows()
    rows[row_index(rows, "turn_outcome")]["kind"] = "answered"
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "turn_outcome_bad_kind" in names(payload)


def test_model_response_attempt_seq_must_start_at_one(tmp_path):
    rows = healthy_rows()
    rows[row_index(rows, "model_response")]["attempt_seq"] = 2
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "model_response_attempt_seq_not_contiguous" in names(payload)


def test_model_response_attempt_seq_must_not_skip(tmp_path):
    rows = healthy_rows()
    extra = dict(rows[row_index(rows, "model_response")])
    extra["attempt_seq"] = 3
    rows.insert(-1, extra)
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "model_response_attempt_seq_not_contiguous" in names(payload)


def test_model_response_attempt_seq_must_not_repeat(tmp_path):
    rows = healthy_rows()
    rows.insert(-1, dict(rows[row_index(rows, "model_response")]))
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "model_response_attempt_seq_duplicate" in names(payload)


def test_model_response_with_an_unknown_status_fails(tmp_path):
    rows = healthy_rows()
    rows[row_index(rows, "model_response")]["status"] = "timeout"
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "model_response_bad_status" in names(payload)


def test_model_response_missing_its_turn_fails(tmp_path):
    rows = healthy_rows()
    del rows[row_index(rows, "model_response")]["turn_id"]
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "model_response_missing_field" in names(payload)


# ------------------------------------------------------------------------ reading the file

def test_a_malformed_line_is_a_named_violation_and_not_a_crash(tmp_path):
    path = write_ledger(tmp_path, healthy_rows())
    with path.open("a") as handle:
        handle.write("{not json at all\n")
        handle.write("[1, 2, 3]\n")
    code, payload = check(path)
    assert code == 1
    assert payload["violation_counts"]["malformed_line"] == 2
    assert payload["counts"]["unparsable_lines"] == 2
    # and the healthy lines around it were still graded
    assert payload["denominators"]["turn_start"] == 1


def test_blank_lines_are_not_a_violation(tmp_path):
    path = write_ledger(tmp_path, healthy_rows())
    path.write_text(path.read_text() + "\n   \n")
    code, payload = check(path)
    assert (code, payload["violations"]) == (0, [])


def test_several_rotations_are_read_as_one_ledger(tmp_path):
    """A turn whose start is in `.1` and whose outcome is in the live file must still pair."""
    rows = healthy_rows()
    split = row_index(rows, "turn_outcome")
    older = write_ledger(tmp_path, rows[:split], name="participation.jsonl.1")
    newer = write_ledger(tmp_path, rows[split:], name="participation.jsonl")
    code, payload = check(older, newer)
    assert (code, payload["violations"]) == (0, [])


def test_a_fragment_downgrades_orphan_joins_to_warnings(tmp_path):
    """Read only the newer half and the join has nothing to join to — but the session's
    `session_start` is missing too, which says the head is in another file, not that the
    emitter misbehaved."""
    rows = healthy_rows()
    split = row_index(rows, "turn_outcome")
    newer = write_ledger(tmp_path, rows[split:])
    code, payload = check(newer)
    assert code == 0, payload["violations"]
    assert {"turn_outcome_orphan", "visible_action_orphan_attempt",
            "stream_render_absent_for_build"} <= warning_names(payload)


def test_an_empty_ledger_is_a_violation(tmp_path):
    path = tmp_path / "participation.jsonl"
    path.write_text("")
    code, payload = check(path)
    assert code == 1
    assert "empty_ledger" in names(payload)


def test_a_missing_file_exits_two(tmp_path):
    result = run_checker(tmp_path / "nope.jsonl", extra=("--json",))
    assert result.returncode == 2
    assert "file_unreadable" in json.loads(result.stdout)["violation_counts"]


# ------------------------------------------------------------------------------ the output

def test_the_human_summary_names_the_violation_with_its_line_number(tmp_path):
    rows = healthy_rows()
    del rows[row_index(rows, "turn_outcome")]
    path = write_ledger(tmp_path, rows)
    result = run_checker(path)
    assert result.returncode == 1
    assert "turn_outcome_missing" in result.stdout
    assert f"{path}:4" in result.stdout          # the turn_start's own line
    assert "verdict: FAIL" in result.stdout
    assert "DO NOT divide one into the other" in result.stdout


def test_the_human_summary_reports_both_denominators(tmp_path):
    result = run_checker(write_ledger(tmp_path, healthy_rows()))
    assert result.returncode == 0
    assert "gate_start" in result.stdout and "turn_start" in result.stdout
    assert "verdict: PASS" in result.stdout


def test_json_and_human_output_agree_on_the_verdict(tmp_path):
    rows = healthy_rows()
    rows[row_index(rows, "turn_outcome")]["kind"] = "answered"
    path = write_ledger(tmp_path, rows)
    human = run_checker(path)
    machine = run_checker(path, extra=("--json",))
    payload = json.loads(machine.stdout)
    assert human.returncode == machine.returncode == 1
    assert payload["ok"] is False and payload["verdict"] == "fail"
    assert "verdict: FAIL" in human.stdout
    assert len(payload["violations"]) == len(
        [ln for ln in human.stdout.splitlines() if "turn_outcome_bad_kind:" in ln]) == 1


def test_quiet_says_nothing_at_all_when_the_ledger_is_clean(tmp_path):
    result = run_checker(write_ledger(tmp_path, healthy_rows()), extra=("--quiet",))
    assert (result.returncode, result.stdout, result.stderr) == (0, "", "")


def test_quiet_still_names_violations(tmp_path):
    rows = healthy_rows()
    del rows[row_index(rows, "gate_start")]
    result = run_checker(write_ledger(tmp_path, rows), extra=("--quiet",))
    assert result.returncode == 1
    assert "visible_action_orphan_attempt" in result.stdout
    assert "denominators" not in result.stdout


def test_every_violation_carries_a_name_a_place_and_a_detail(tmp_path):
    """A 2am reader gets a name to grep, a line to open, and a sentence saying what joined to
    nothing. A finding missing any of the three is not actionable."""
    rows = healthy_rows()
    del rows[row_index(rows, "turn_outcome")]
    rows[row_index(rows, "outbound_receipt")]["op"] = "nope"
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert len(payload["violations"]) >= 2
    for finding in payload["violations"]:
        assert finding["name"] and finding["detail"]
        assert finding["file"] and finding["line"] > 0


@pytest.mark.parametrize("flag", ["--json", "--quiet"])
def test_the_cli_never_writes_to_stderr_on_a_ledger_it_understands(tmp_path, flag):
    result = run_checker(write_ledger(tmp_path, healthy_rows()), extra=(flag,))
    assert result.stderr == ""


# ---------------------------------------------------------- DM reconsiderations (ruling 8)
#
# A DM's stale draft goes through the same reconsideration runner as a channel's, so its passes
# obey the same arithmetic — and a DM will NEVER have a `turn_start` to join. Declining to grade
# unjoined rows would mean the DM population is never checked at all.


def dm_reconsideration_rows(session=SESSION, *, passes=1):
    """One DM turn whose draft was suppressed, reviewed in `passes` passes, and posted."""
    turn_id = f"t-dm-{session}"
    rows = [envelope("session_start", session=session, build="deadbee")]
    for index in range(passes):
        rows.append(envelope("stale_send", session=session, channel_id="D9", trigger_ts="1.0",
                             turn_id=turn_id, last_seen_ts="1.0", observed_latest_ts="2.0",
                             scope="top", surface="final_post", guard_mode="start_only"))
        rows.append(envelope("reconsider_start", session=session, channel_id="D9",
                             trigger_ts="1.0", turn_id=turn_id, scope=["top", "D9", "U1"],
                             observed_latest_ts="2.0", model_attempt_seq=index + 1,
                             **{"pass": index + 1}))
    rows.append(envelope("reconsider_outcome", session=session, channel_id="D9",
                         trigger_ts="1.0", turn_id=turn_id, outcome="posted_asis",
                         passes=passes, forced=False))
    rows.append(envelope("session_end", session=session))
    return rows


def test_a_dm_reconsideration_is_graded_rather_than_reported_as_an_orphan(tmp_path):
    code, payload = check(write_ledger(tmp_path, dm_reconsideration_rows(passes=2)))
    assert (code, names(payload)) == (0, set())
    assert "reconsider_start_orphan_turn" not in warning_names(payload)
    assert "reconsider_outcome_orphan_turn" not in warning_names(payload)


def test_a_dm_reconsideration_with_miscounted_passes_fails_by_name(tmp_path):
    rows = dm_reconsideration_rows(passes=2)
    rows[row_index(rows, "reconsider_outcome")]["passes"] = 5
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "reconsider_outcome_passes_mismatch" in names(payload)


def test_a_channel_reconsideration_with_no_turn_start_is_still_only_a_warning(tmp_path):
    """The rotated-file exemption is unchanged for CHANNEL turns: a sequence whose head is in
    `participation.jsonl.1` must not be graded as a gap."""
    rows = dm_reconsideration_rows()
    for row in rows:
        if row.get("channel_id") == "D9":
            row["channel_id"] = "C1"
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 0
    assert "reconsider_start_orphan_turn" in warning_names(payload)


def test_a_dm_reconsideration_attempt_sequence_is_graded_without_a_turn_start(tmp_path):
    """`model_response` carries no channel_id, so the DM classification has to come from the
    turn's other rows. An older ledger (written before DM turns joined the population) has the
    reconsider rows and no turn_start — and its one attempt sequence must still be graded."""
    rows = dm_reconsideration_rows()
    turn_id = rows[row_index(rows, "reconsider_outcome")]["turn_id"]
    rows.insert(-1, envelope("model_response", turn_id=turn_id, attempt_seq=2, status="ok",
                             model="gpt-5.6-sol", fork_reason="stale_reconsideration"))
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "model_response_attempt_seq_not_contiguous" in names(payload)
    assert "model_response_orphan_turn" not in warning_names(payload)


def test_an_enterprise_grid_user_addressed_dm_reads_as_a_dm(tmp_path):
    """A Slack user id is "W…" on Enterprise Grid, and an outbound DM can be addressed by it.
    Missing that prefix put those turns back in the orphan bucket."""
    rows = dm_reconsideration_rows()
    for row in rows:
        if row.get("channel_id") == "D9":
            row["channel_id"] = "W123"
    code, payload = check(write_ledger(tmp_path, rows))
    assert (code, names(payload)) == (0, set())
    assert "reconsider_start_orphan_turn" not in warning_names(payload)


def test_dm_turns_are_counted_apart_from_channel_turns(tmp_path):
    """Two populations, two denominators, never divided into each other — the rule the gate and
    turn counts already follow, extended to the surface that just joined."""
    rows = healthy_rows() + [
        envelope("turn_start", channel_id="D9", trigger_ts="1.0", turn_id="t-dm",
                 surface="dm", gated=False),
        envelope("turn_outcome", channel_id="D9", trigger_ts="1.0", turn_id="t-dm",
                 kind="reply", chars=4, stream_build_present=False, destinations=[], edits=[]),
    ]
    code, payload = check(write_ledger(tmp_path, rows))
    assert (code, names(payload)) == (0, set())
    assert payload["denominators"]["turn_start"] == 1        # channel only
    assert payload["denominators"]["turn_start_dm"] == 1
    assert payload["denominators"]["turn_outcome_dm"] == 1


def dm_fragment_rows(rows):
    """The same rows read as a ROTATED FRAGMENT: the session_start is in participation.jsonl.1,
    so the head of every sequence may be too."""
    return [row for row in rows if row["event"] != "session_start"]


def test_a_rotated_dm_fragment_is_not_graded_as_a_gap(tmp_path):
    """A fragment can cut a DM's first pass and first attempt off the top of the file. Grading
    what is left would fail a healthy turn for starting at 3 — the exact exemption channel turns
    already had, and the one DMs were missing."""
    rows = dm_reconsideration_rows(passes=2)
    turn_id = rows[row_index(rows, "reconsider_outcome")]["turn_id"]
    # Drop pass 1 and its suppression, and record the outcome over the passes that survived —
    # i.e. exactly what a rotated head looks like from here.
    rows = [row for row in rows
            if not (row["event"] in ("reconsider_start", "stale_send")
                    and row.get("pass", 1) == 1)]
    rows.insert(-1, envelope("model_response", turn_id=turn_id, attempt_seq=2, status="ok",
                             model="gpt-5.6-sol", fork_reason="stale_reconsideration"))
    code, payload = check(write_ledger(tmp_path, dm_fragment_rows(rows)))

    assert (code, names(payload)) == (0, set()), payload["violations"]
    assert {"reconsider_start_orphan_turn", "model_response_orphan_turn"} <= warning_names(
        payload)


def test_a_complete_dm_session_is_still_graded(tmp_path):
    """The mutation of the test above: with the session_start present nothing is exempt, and the
    same truncated sequence fails."""
    rows = dm_reconsideration_rows(passes=2)
    rows = [row for row in rows
            if not (row["event"] in ("reconsider_start", "stale_send")
                    and row.get("pass", 1) == 1)]
    code, payload = check(write_ledger(tmp_path, rows))
    assert code == 1
    assert "reconsider_pass_not_contiguous" in names(payload)
